root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_registration_register
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
