<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
    public function map_json($map)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT l.lat as latitude, l.lng as longitude, p.title, p.body as content FROM AppBundle:Point p JOIN p.location l WHERE p.map = ?1 ')->setParameter('1', $map)->getResult();
    }
}
