<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
    public function map_json($map)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT l.lat as latitude, l.lng as longitude, f.title, f.id, f.body as content FROM AppBundle:File f JOIN f.location l WHERE l.map = ?1 and f.status = 1')->setParameter('1', $map)->getResult();
    }
}
